//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_INVOICE
    {
        public System.Guid InvoiceID { get; set; }
        public string Invoice { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public string Invoice2 { get; set; }
        public Nullable<System.DateTime> Day2 { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> DiscountAmount { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string Description { get; set; }
        public string CompanyID { get; set; }
        public string DepartmentID { get; set; }
        public string ReceivingDepartmentID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> RestoredDate { get; set; }
    }
}
