//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InvoiceDetail
    {
        public System.Guid InvoiceDetai_ID { get; set; }
        public Nullable<System.Guid> InvoiceID { get; set; }
        public string BARCODE { get; set; }
        public string QRCODE { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> SubtotalAmount { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
    }
}
