//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Inventory
    {
        public System.Guid InventoryID { get; set; }
        public Nullable<int> PeriodYear { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Period { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<int> BeginningQuantity { get; set; }
        public Nullable<int> ReceivedQuantity { get; set; }
        public Nullable<int> IssuedQuantity { get; set; }
        public Nullable<int> FinalQuantity { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
