//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SYS_REPORT
    {
        public int REP_CODE { get; set; }
        public string Description { get; set; }
        public string RepName { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> FromDate { get; set; }
        public Nullable<bool> MonthYear { get; set; }
        public Nullable<bool> CompanyID { get; set; }
        public Nullable<bool> DepartmentID { get; set; }
    }
}
