//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_REP_SYS_RIGHT_REP
    {
        public int REP_CODE { get; set; }
        public string RepName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Visible { get; set; }
        public int UserID { get; set; }
        public string Access { get; set; }
    }
}
